<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "order".
 *
 * @property int $id
 * @property string|null $name_uz
 * @property string|null $name_ru
 * @property string|null $name_en
 * @property int|null $cargo_type
 * @property int|null $cargo_from_location
 * @property int|null $cargo_to_location
 * @property int|null $status
 * @property int|null $currently_location
 * @property string|null $delivery_time
 * @property string|null $created_at
 * @property string|null $updated_at
 */
class Order extends \yii\db\ActiveRecord
{
    const SENDING = 1;
    const NEW = 5;
    const REVIEW = 6;
    const SENT = 2;
    const CUSTOM = 3;
    const DELIVERED = 4;
    const CANCELLED = -1;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'updated_by'], 'integer'],
            [['cargo_type', 'cargo_from_location', 'cargo_to_location',
                'name_uz', 'name_ru', 'name_en', 'delivery_time', 'created_at', 'currently_location',
                'updated_at', 'whom', 'how', 'mass', 'order_code',
                'phone', 'email', 'doc', 'client_name', 'price', 'code'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name_uz' => 'Наименование груза',
            'name_ru' => 'Наименование груза',
            'name_en' => 'Наименование груза',
            'cargo_type' => 'Объем/размеры',
            'cargo_from_location' => 'Откуда',
            'cargo_to_location' => 'Куда',
            'status' => 'Статус',
            'currently_location' => 'Город расположения груза',
            'delivery_time' => 'Примерная дата доставки',
            'created_at' => 'Создано',
            'updated_at' => 'Обновлено',
            'client_name' => 'Ф.И.О. клиента',
            'phone' => 'Номер телефона',
            'code' => 'Код ТНВЭД',
            'mass' => 'Вес',
            'price' => 'Стоимость',
            'order_code' => 'Код заказа',

        ];
    }

    public static function getAllStatus($item = null)
    {
        $status = [
            self::NEW => 'Новый',
            self::REVIEW => 'На рассмотрении',
            self::SENDING => 'Отправляется',

            self::SENT => 'В Пути',
            self::CUSTOM => 'На Таможенном контроле',
            self::DELIVERED => 'Доставлено',
            self::CANCELLED => 'Отменено',
        ];
        return $item ? $status[$item] : $status;
    }

    public function getStatus()
    {

        $status = [
            self::NEW => 'Новый',
            self::REVIEW => 'На рассмотрении',
            self::SENDING => 'Отправляется',
            self::SENT => 'В Пути',
            self::CUSTOM => 'На Таможенном контроле',
            self::DELIVERED => 'Доставлено',
            self::CANCELLED => 'Отменено',
        ];
        return $this->status ? $status[$this->status] : $status;
    }

    public function getStatusFront()
    {

        $status = [
            self::NEW => 'Новый',
            self::REVIEW => 'На рассмотрении',
            self::SENDING => 'Отправляется',
            self::SENT => 'В Пути',
            self::CUSTOM => 'На Таможенном контроле',
            self::DELIVERED => 'Доставлено',
            self::CANCELLED => 'Отменено',
        ];
        return $this->status ? $status[$this->status] : '';
    }

    public function getCountries()
    {

        return $this->hasOne(Country::className(), ['id' => 'cargo_from_location']);
    }

    public function getRegions()
    {

        return $this->hasOne(Country::className(), ['id' => 'cargo_to_location']);
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $generateDoc_Conclusion = Yii::$app->security->generateRandomString(5);
            $this->order_code = $generateDoc_Conclusion;
            $this->status = Order::NEW;


        }
        if (!$this->isNewRecord) {
            $mydate = strtotime($this->delivery_time);
            $this->delivery_time = (int)$mydate;
        }

        return parent::beforeSave($insert);
    }

}
