<?php

namespace common\models;

use DateTime;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\TemplateProcessor;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/**
 * This is the model class for table "order".
 *
 * @property int $id
 * @property string|null $name_uz
 * @property string|null $name_ru
 * @property string|null $name_en
 * @property int|null $cargo_type
 * @property int|null $cargo_from_location
 * @property int|null $cargo_to_location
 * @property int|null $status
 * @property int|null $currently_location
 * @property string|null $delivery_time
 * @property string|null $created_at
 * @property string|null $updated_at
 */
class Order extends \yii\db\ActiveRecord
{
    const SENDING = 1;
    const NEW = 5;
    const REVIEW = 6;
    const SENT = 2;
    const CUSTOM = 3;
    const DELIVERED = 4;
    const CANCELLED = -1;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'updated_by'], 'integer'],
            [['cargo_type', 'cargo_from_location', 'cargo_to_location', 'client_name', 'phone', 'code', 'mass', 'name_ru',], 'required', 'message' => 'Поля пустой !'],
            [['cargo_type', 'cargo_from_location', 'cargo_to_location',
                'name_uz', 'name_ru', 'name_en', 'delivery_time', 'created_at', 'currently_location',
                'updated_at', 'whom', 'how', 'mass', 'order_code',
                'phone', 'email', 'doc', 'client_name', 'price', 'code'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name_uz' => 'Наименование груза',
            'name_ru' => 'Наименование груза',
            'name_en' => 'Наименование груза',
            'cargo_type' => 'Вид транспорта',
            'cargo_from_location' => 'Откуда',
            'cargo_to_location' => 'Куда',
            'status' => 'Статус',
            'currently_location' => 'Город расположения груза',
            'delivery_time' => 'Примерная дата доставки',
            'created_at' => 'Создано',
            'updated_at' => 'Обновлено',
            'client_name' => 'Ф.И.О. клиента',
            'phone' => 'Номер телефона',
            'code' => 'Код ТНВЭД',
            'mass' => 'Объем/размеры',
            'price' => 'Стоимость',
            'order_code' => 'Код заказа',

        ];
    }

    public static function getAllStatus($item = null)
    {
        $status = [
            self::NEW => 'Новый',
            self::REVIEW => 'На рассмотрении',
            self::SENDING => 'Отправляется',

            self::SENT => 'В Пути',
            self::CUSTOM => 'На Таможенном контроле',
            self::DELIVERED => 'Доставлено',
            self::CANCELLED => 'Отменено',
        ];
        return $item ? $status[$item] : $status;
    }

    public function getStatus()
    {

        $status = [
            self::NEW => 'Новый',
            self::REVIEW => 'На рассмотрении',
            self::SENDING => 'Отправляется',
            self::SENT => 'В Пути',
            self::CUSTOM => 'На Таможенном контроле',
            self::DELIVERED => 'Доставлено',
            self::CANCELLED => 'Отменено',
        ];
        return $this->status ? $status[$this->status] : $status;
    }

    public function getStatusFront()
    {

        $status = [
            self::NEW => 'Новый',
            self::REVIEW => 'На рассмотрении',
            self::SENDING => 'Отправляется',
            self::SENT => 'В Пути',
            self::CUSTOM => 'На Таможенном контроле',
            self::DELIVERED => 'Доставлено',
            self::CANCELLED => 'Отменено',
        ];
        return $this->status ? $status[$this->status] : '';
    }

    public function getCountries()
    {

        return $this->hasOne(Country::className(), ['id' => 'cargo_from_location']);
    }

    public function getRegions()
    {

        return $this->hasOne(Country::className(), ['id' => 'cargo_to_location']);
    }

    public function getType()
    {

        return $this->hasOne(TypeTransport::className(), ['id' => 'cargo_type']);
    }

    public function getAllType()
    {

        $transport = TypeTransport::find()->all();
        if ($transport) {

            $transport = ArrayHelper::map($transport, 'id', 'name_ru');
            return $transport;
        }
    }


    public function getCurrently()
    {
        if ($this->currently_location) {
            $res = Country::find()->where(['id' => $this->currently_location])->one();
        } else {
            $res = Country::find()->where(['id' => $this->cargo_from_location])->one();

        }

        return [$res->parent->name_ru ?? '', $res->name_ru ?? ''];
    }

    public function getLocations()
    {
        $res = Country::findOne($this->currently_location);
        if ($res)
            return [$res->long, $res->lat];

        return [];
    }

    public function beforeSave($insert)
    {


        if ($this->isNewRecord) {
            $generateDoc_Conclusion = Yii::$app->security->generateRandomString(5);
            $this->order_code = $generateDoc_Conclusion;
            $this->status = Order::NEW;

        }

        $mydate = strtotime($this->delivery_time);

        if ($mydate) {
            $this->delivery_time = $mydate;
        }

        if ($this->status == Order::NEW && $this->price && $this->delivery_time) {
            $this->status = Order::REVIEW;
        }

        return parent::beforeSave($insert);
    }

    public function generateCheckOrder()
    {
        $item = Order::find()
            ->where([
                'id' => $this->id
            ])
            ->one();

        $phpWord = new PHPWord();
        $folder = '/web/uploads/temp/';
        $uploads_folder = Yii::getAlias('@frontend') . $folder;
        if (!file_exists($uploads_folder)) {
            mkdir($uploads_folder, 0777, true);
        }

        \PhpOffice\PhpWord\Settings::setTempDir($uploads_folder);

        $templateProcessor = new TemplateProcessor(Yii::getAlias('@frontend') . '/web/uploads/word/order.docx');
        $templateProcessor->setValue('from', $item->countries->name_ru);
        $templateProcessor->setValue('to', $item->regions->name_ru);
        $templateProcessor->setValue('price', $item->price);
        $templateProcessor->setValue('type', $item->type->name_ru);
        $templateProcessor->setValue('код', $item->order_code);
        $templateProcessor->setValue('name', $item->name_ru);

        if ($item->delivery_time) {
            $time1 = new DateTime(date("d-m-Y"));
            $time2 = new DateTime(date('d-m-Y', $item->delivery_time));
            $interval = $time1->diff($time2);
            $templateProcessor->setValue('длительность', $interval->format('%d день'));;
        }

        $filename = Yii::getAlias('@frontend') . '/web/uploads/word/' . $item->order_code . '.docx';
        $this->doc = 'uploads/word/' . $item->order_code . '.docx';

        $this->save();

        $templateProcessor->saveAs($filename);

        if ($filename)
            chmod($filename, 0644);

    }

//    public function afterSave($insert, $changedAttributes)
//    {
//        parent::afterSave($insert, $changedAttributes);
//
//        dd($changedAttributes);
//
//    }


}
