<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "order_about".
 *
 * @property int $id
 * @property int|null $status
 * @property string|null $country
 * @property string|null $name_ru
 * @property string|null $name_uz
 * @property string|null $name_en
 * @property string|null $region
 * @property int|null $delivery_time
 * @property string|null $order_code
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property string|null $long
 * @property string|null $lat
 * @property string|null $truck_id
 */
class OrderAbout extends \yii\db\ActiveRecord
{


    const SENDING = 1;
    const SENT = 2;
    const CUSTOM = 3;
    const DELIVERED = 4;
    const CANCELLED = -1;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order_about';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['country', 'name_ru', 'name_uz', 'name_en', 'region', 'order_code', 'long', 'lat', 'delivery_time',
                'truck_id', 'phone', 'email', 'cargo_type', 'cargo_from_location', 'cargo_to_location', 'currently_location'
            ], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'country' => 'Country',
            'name_ru' => 'Name Ru',
            'name_uz' => 'Name Uz',
            'name_en' => 'Name En',
            'region' => 'Region',
            'delivery_time' => 'Delivery Time',
            'order_code' => 'Order Code',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'long' => 'Long',
            'lat' => 'Lat',
            'truck_id' => 'Truck ID',
        ];
    }

    public static function getAllStatus($item = null)
    {
        $status = [
            self::SENDING => 'Отправляется',
            self::SENT => 'В Пути',
            self::CUSTOM => 'На Таможенном контроле',
            self::DELIVERED => 'Доставлено',
            self::CANCELLED => 'Отменено',
        ];
        return $item ? $status[$item] : $status;
    }
    public  function getStatus()
    {

        $status = [
            self::SENDING => 'Отправляется',
            self::SENT => 'В Пути',
            self::CUSTOM => 'На Таможенном контроле',
            self::DELIVERED => 'Доставлено',
            self::CANCELLED => 'Отменено',
        ];
        return $this->status ? $status[$this->status] : $status;
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $generateDoc_Conclusion = Yii::$app->security->generateRandomString(5);
            $this->truck_id = $generateDoc_Conclusion;
        }

        $mydate = strtotime($this->delivery_time);
        $this->delivery_time = (int)$mydate;
        return parent::beforeSave($insert);
    }

    public function getCountries()
    {

        return $this->hasOne(Country::className(), ['id' => 'country']);
    }
    public function getRegions()
    {

        return $this->hasOne(Country::className(), ['id' => 'region']);
    }
}
